title: And So It Begins
author: Alis-bit
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  And So It Begins is a blog about learning to code from scratch to become a developer, where I talk about my experiences and my projects.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
